In [1]:
import torch

In [2]:
# Periksa apakah CUDA (GPU) tersedia
if torch.cuda.is_available():
    # Dapatkan jumlah GPU yang tersedia
    num_gpus = torch.cuda.device_count()
    print(f"Jumlah GPU yang tersedia: {num_gpus}")

    # Tampilkan informasi tentang GPU yang sedang digunakan
    current_device = torch.cuda.current_device()
    device_name = torch.cuda.get_device_name(current_device)
    print(f"GPU yang sedang digunakan: {device_name}")
else:
    print("CUDA (GPU) tidak tersedia.")

Jumlah GPU yang tersedia: 1
GPU yang sedang digunakan: NVIDIA GeForce RTX 3050 Laptop GPU


In [3]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 42,  93,  76, -26,  57, -88])

In [4]:
tensor = torch.tensor([[0.1,1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
# melihat perangkat GPU
device = 'cude' if torch.cuda.is_available() else 'cpu'
print(device)

cude


In [14]:
device = torch.device('cuda')

In [15]:
import numpy as np
import time

In [16]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0010101795


In [17]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

3.63966990
0.1830909252


In [18]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

# Draw 5 simples from the multinominal ditribusi
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])


In [19]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [20]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [22]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [23]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [24]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [25]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias= False)
print(linear(sample))

tensor([-0.2778,  1.6543, -3.6907], grad_fn=<SqueezeBackward4>)


In [27]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# Apply softmax using torch.nn.functional.softmax
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [28]:
# initialize on embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# create same input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedding_output = embedding(input_indices)

# the output will be a Tensor of shape(4, 100), where 4 is the number of input
# and 100 is the dimensionality of the embedding vectors
print(embedding_output.shape)
print(embedding_output)

torch.Size([4, 6])
tensor([[-0.8722,  0.6991, -1.2483,  0.3776,  0.8410, -2.5456],
        [ 0.1200, -1.7482,  0.6709, -0.7113, -0.2979, -0.1356],
        [-0.0405, -1.0103,  0.0365,  1.0391, -1.5683,  0.4804],
        [-0.3192,  1.6441, -0.6218, -0.1432, -1.3910, -2.1468]],
       grad_fn=<EmbeddingBackward0>)


In [29]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print( a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [30]:
# type int64
int_64 = torch.randint(1, (3,2)).float()
# type float32
float_32 = torch.rand(2,3)
#print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [31]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
#print(a.shape)
print(x,y,z)

torch.Size([2, 3, 5])
2 3 5


In [34]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T, C)
print(output)
#print(input)
#print(output[:, -1, :])
last_column = output[:, -1]

tensor([[8.8553e-01, 2.1199e-01, 3.0790e-01, 1.5432e-01, 9.5750e-01, 6.4523e-01,
         6.0878e-01, 2.2314e-01, 3.7194e-01, 8.3655e-01],
        [6.4646e-01, 2.9468e-01, 4.0354e-02, 2.1891e-01, 3.2832e-01, 3.5151e-01,
         2.9318e-01, 4.7442e-01, 2.2846e-01, 3.2745e-01],
        [1.1670e-01, 4.2423e-01, 2.3683e-01, 2.2944e-01, 8.1319e-01, 5.7446e-01,
         4.0404e-01, 7.0976e-01, 4.2384e-01, 7.6167e-01],
        [1.8744e-01, 1.1892e-01, 5.6408e-01, 6.7910e-01, 1.3561e-01, 9.3158e-01,
         3.7891e-01, 7.2196e-03, 8.2670e-01, 2.7359e-02],
        [6.2443e-01, 9.8999e-01, 6.2253e-01, 8.8868e-01, 5.7025e-01, 5.3440e-01,
         9.9165e-01, 3.0417e-02, 1.9107e-01, 3.5771e-01],
        [5.2448e-01, 6.2341e-01, 6.8300e-01, 3.7448e-01, 5.6402e-01, 7.7378e-01,
         5.6850e-01, 2.8285e-01, 9.6824e-01, 3.4256e-01],
        [1.1767e-01, 4.2722e-01, 9.3571e-01, 6.9583e-01, 7.7960e-01, 2.4125e-01,
         7.6814e-01, 4.3383e-01, 2.9966e-01, 9.8439e-01],
        [1.6539e-01, 1.9626