In [35]:
import torch

In [36]:
# Periksa apakah CUDA (GPU) tersedia
if torch.cuda.is_available():
    # Dapatkan jumlah GPU yang tersedia
    num_gpus = torch.cuda.device_count()
    print(f"Jumlah GPU yang tersedia: {num_gpus}")

    # Tampilkan informasi tentang GPU yang sedang digunakan
    current_device = torch.cuda.current_device()
    device_name = torch.cuda.get_device_name(current_device)
    print(f"GPU yang sedang digunakan: {device_name}")
else:
    print("CUDA (GPU) tidak tersedia.")

Jumlah GPU yang tersedia: 1
GPU yang sedang digunakan: NVIDIA GeForce RTX 3050 Laptop GPU


In [37]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-74,  63, -91,  82, -46, -48])

In [38]:
tensor = torch.tensor([[0.1,1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [39]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [40]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
input = torch.empty(2,3)
input

tensor([[ 3.0000,  4.7500,  6.5000],
        [ 8.2500, 10.0000,  0.0000]])

In [42]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [43]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [44]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [45]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [46]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[4575657222473777152, 4575657222473777152, 4575657222473777152],
        [4575657222473777152, 4575657222473777152, 4575657222473777152]])

In [47]:
# melihat perangkat GPU
device = 'cude' if torch.cuda.is_available() else 'cpu'
print(device)

cude


In [48]:
device = torch.device('cuda')

In [49]:
import numpy as np
import time

In [50]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0010113716


In [51]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.04569459
0.1259393692


In [52]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

# Draw 5 simples from the multinominal ditribusi
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 1])


In [53]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [54]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [55]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [56]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [57]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [58]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [59]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias= False)
print(linear(sample))

tensor([ 8.0206, 10.3018, -4.7118], grad_fn=<SqueezeBackward4>)


In [61]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# Apply softmax using torch.nn.functional.softmax
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [62]:
# initialize on embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# create same input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedding_output = embedding(input_indices)

# the output will be a Tensor of shape(4, 100), where 4 is the number of input
# and 100 is the dimensionality of the embedding vectors
print(embedding_output.shape)
print(embedding_output)

torch.Size([4, 6])
tensor([[ 1.4984,  1.1955, -1.4528, -0.4856,  0.2816,  0.5452],
        [ 0.4629, -0.5137,  1.1773, -0.4471, -0.6302,  0.5282],
        [-0.0100,  0.2727,  2.3499,  1.0518,  0.8267,  0.7499],
        [ 2.2715,  0.0515, -0.0751,  1.1689,  0.3511, -0.4781]],
       grad_fn=<EmbeddingBackward0>)


In [63]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print( a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [64]:
# type int64
int_64 = torch.randint(1, (3,2)).float()
# type float32
float_32 = torch.rand(2,3)
#print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [65]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
#print(a.shape)
print(x,y,z)

torch.Size([2, 3, 5])
2 3 5


In [66]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T, C)
print(output)
#print(input)
#print(output[:, -1, :])
last_column = output[:, -1]

tensor([[0.6162, 0.1937, 0.9112, 0.6302, 0.0290, 0.7109, 0.4907, 0.8285, 0.9830,
         0.4421],
        [0.1691, 0.8901, 0.9002, 0.4778, 0.6776, 0.2973, 0.4545, 0.2770, 0.8290,
         0.3365],
        [0.0017, 0.3868, 0.9970, 0.5678, 0.7368, 0.9889, 0.1052, 0.6653, 0.1053,
         0.6363],
        [0.3431, 0.9832, 0.5434, 0.6817, 0.4872, 0.1235, 0.5305, 0.4286, 0.3383,
         0.4707],
        [0.3263, 0.1104, 0.7143, 0.6885, 0.7659, 0.1008, 0.0779, 0.8334, 0.8286,
         0.1163],
        [0.2609, 0.2499, 0.8119, 0.4298, 0.1213, 0.9176, 0.1310, 0.9867, 0.4495,
         0.3186],
        [0.2870, 0.3308, 0.3611, 0.3251, 0.8186, 0.2167, 0.4664, 0.9501, 0.3704,
         0.9745],
        [0.4005, 0.6098, 0.5579, 0.3510, 0.9011, 0.7223, 0.6827, 0.8189, 0.1530,
         0.0926],
        [0.2136, 0.4295, 0.2711, 0.6960, 0.0533, 0.2293, 0.6921, 0.3045, 0.2360,
         0.3967],
        [0.4449, 0.6243, 0.3657, 0.7925, 0.2968, 0.9304, 0.2008, 0.1405, 0.6886,
         0.4977],
        [0

In [67]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = nn.ReLU(x)
print(y)

ReLU(inplace=True)


In [68]:
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [69]:
y = F.tanh(x)
print(y)

tensor([-0.0500])
